export const mockPhoneData = {
  data: {
    uid: "a1a1a1a1-b2b2-c3c3-d4d4-e5e5e5e5e5e5",
    phone: "+12223334444",
    title: "John Doe",
    summary: "Sample individual for testing",
    country: "us",
    website: "https://example.com",
    type: "Person",
    category: "Test Category",
    other_categories: ["Example"],
    keywords: ["sample", "test"],
    other_titles: ["Tester"],
    other_websites: ["https://example.com"],
    address: "123 Main St",
    locality: "Downtown",
    city: "Nashville",
    state: "TN",
    zip: "37027",
    email: "hello@example.com",
    social_media_profiles: ["https://twitter.com/example"],
  },
  trust: "Verified",
  credits: 0,
};
